const socialVolunteerBase = '/social/volunteer';

export const routes = {
  home: '/',
  login: '/login',
  register: '/register',
  logout: '/logout',
  onboarding: '/onboarding',
  onboardingVision: '/onboarding/vision',
  dashboard: '/dashboard',
  profile: '/profile',
  profileEdit: '/profile/edit',
  roleSettings: '/profile/role',
  tutorialHome: '/tutorial',
  tutorialRules: '/tutorial/rules',
  tutorialEquipment: '/tutorial/equipment',
  tutorialTerms: '/tutorial/terms',
  tutorialSafety: '/tutorial/safety',
  accessibilityHub: '/accessibility',
  voiceMode: '/accessibility/voice',
  focusPreview: '/accessibility/focus-preview',
  scanWall: '/climb/scan',
  selectDifficulty: '/climb/difficulty',
  routeRecommendation: '/climb/route',
  liveGuidance: '/climb/live',
  climbSummary: '/climb/summary',
  socialFeed: '/social',
  createPost: '/social/new',
  myPosts: '/social/my',
  socialFriends: '/social/friends',
  socialRooms: '/social/rooms',
  volunteerBoard: socialVolunteerBase,
  volunteerCreate: `${socialVolunteerBase}/new`,
  volunteerMySessions: `${socialVolunteerBase}/my-sessions`,
  contactIntent: `${socialVolunteerBase}/contact-intent`,
  volunteerPostDetail: (postId: string) => `${socialVolunteerBase}/${postId}`,
  forbidden: '/403',
};
